spring:
  application:
    name: review-service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  data-source:
    url: jdbc:h2:mem:testdb
    drvierClassName: org.h2.Driver
    username: sa
    password: password

eureka:
  client:
    enabled: false